version: "3.8"

services:

  db:
    image: postgres:13.3
    container_name: postgres
    volumes:
    - data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: student
      POSTGRES_PASSWORD: student
      POSTGRES_DB: studentdb
    ports:
    - 5432

volumes:
  data:
